Spectrum one ccd dev
soleil-ica/Lima-tango-cpp pull request #32
Opened 2021-03-12 15:44 UTC by hott-onin

Integration of SpectrumOneCCD specific device and its documentation

2021-03-16 17:54 UTC, soleil-ica requested changes

2021-03-16 17:54 UTC, soleil-ica commented on doc/SpectrumOneCCD/spectrumoneccd.rst
> +GpibAddress             0                                       Long            Gpib Address of the controller (from 0 to 30).
Attention: confusion possible pour le controller en GPIB et IP/port

2021-03-16 17:54 UTC, soleil-ica commented on doc/SpectrumOneCCD/spectrumoneccd.rst
> +lastTemperature         Read            Double          Last temperature of the CCD.
pourquoi pas "temperature" sans le last?

2021-03-16 17:54 UTC, soleil-ica commented on doc/SpectrumOneCCD/spectrumoneccd.rst
> +ForcedInit              Void            Void            Force the initialization, injection of the tables and the re-configuration of the camera.
Quelle est la diff entre ForcedInit (que j'appelerais plutot ForceInit) et Init ?

2021-03-16 17:54 UTC, soleil-ica commented on doc/SpectrumOneCCD/spectrumoneccd.rst
> +GetGain                 Void            Void            Get the temperature of the camera.
erreur dans la description

2021-03-16 17:54 UTC, soleil-ica commented on doc/SpectrumOneCCD/spectrumoneccd.rst
> +ReConfig                Void            Void            Force the re-configuration of the camera.
Pourquoi pas "Configure" ou "ForceConfig"

2021-03-16 17:54 UTC, soleil-ica commented on specifics/SpectrumOneCCD/SpectrumOneCCD.cpp
> +    CREATE_SCALAR_ATTRIBUTE(attr_gain_read);
tu peux faire plutot:
CREATE_SCALAR_ATTRIBUTE(attr_lastTemperature_read,0);
et enlever 
*attr_lastTemperature_read = 0;

2021-03-16 17:54 UTC, soleil-ica commented on specifics/SpectrumOneCCD/SpectrumOneCCD.cpp
> +    //     yat4tango::InnerAppender::initialize(this, 512);
non fonctionnel?

2021-03-16 17:54 UTC, soleil-ica commented on specifics/SpectrumOneCCD/SpectrumOneCCD.cpp
> +
code  à mettre dans le always: 
```
try
    {
        yat::AutoMutex<> _lock(ControlFactory::instance().get_global_mutex());
        m_status_message.str("");
        //- get the singleton control objet used to pilot the lima framework
        m_ct = ControlFactory::instance().get_control("ImXpad");

        //- get interface to specific camera
        m_hw = dynamic_cast<imXpad::Interface*> (m_ct->hwInterface());

        //- get camera to specific detector
        m_camera = &(m_hw->getCamera());

        //update state
        dev_state();
    }
    catch (Exception& e)
    {
        ERROR_STREAM << e.getErrMsg() << endl;
        m_status_message << "Initialization Failed : " << e.getErrMsg() << endl;
        //- throw exception
        set_state(Tango::FAULT);
        m_is_device_initialized = false;
        return;
    }
    catch (...)
    {
        ERROR_STREAM << "Initialization Failed : UNKNOWN" << endl;
        m_status_message << "Initialization Failed : UNKNOWN" << endl;
        //- throw exception
        set_state(Tango::FAULT);
        m_is_device_initialized = false;
        return;
    }
```

2021-03-16 17:54 UTC, soleil-ica commented on specifics/SpectrumOneCCD/SpectrumOneCCD.cpp
> +
Ne faut il pas memoriser le gain? si oui: créer une prop __MemorizedGain et la reappliquer à l'init : eg:

```
  Tango::WAttribute &mode = dev_attr->get_w_attr_by_name("mode");
    	m_mode = __MemorizedMode;
    	attr_mode_write = const_cast<Tango::DevString>(__MemorizedMode.c_str());
    	mode.set_write_value(attr_mode_write);
    	write_mode(mode);
```

2021-03-16 17:54 UTC, soleil-ica commented on specifics/SpectrumOneCCD/SpectrumOneCCD.cpp
> +    m_camera->getTemperature(*attr_lastTemperature_read);
il faut mettre des try catch + un lock: eg:
```
void ImXpad::read_flatFieldCorrectionFlag(Tango::Attribute &attr)
{
	DEBUG_STREAM << "ImXpad::read_flatFieldCorrectionFlag(Tango::Attribute &attr) entering... "<< endl;
    yat::AutoMutex<> _lock(ControlFactory::instance().get_global_mutex());
    try
    {
        *attr_flatFieldCorrectionFlag_read = static_cast<Tango::DevBoolean>(m_camera->getFlatFieldCorrectionFlag());
        attr.set_value(attr_flatFieldCorrectionFlag_read);
    }
    catch(Tango::DevFailed& df)
    {
        ERROR_STREAM << df << endl;
        //- rethrow exception
        Tango::Except::re_throw_exception(df,
                                          "TANGO_DEVICE_ERROR",
                                          std::string(df.errors[0].desc).c_str(),
                                          "ImXpad::read_flatFieldCorrectionFlag");
    }
    catch(Exception& e)
    {
        ERROR_STREAM << e.getErrMsg() << endl;
        m_status_message.str("");
        m_status_message << e.getErrMsg().c_str() << endl;
        //- throw exception
        Tango::Except::throw_exception("TANGO_DEVICE_ERROR",
                                       e.getErrMsg().c_str(),
                                       "ImXpad::read_flatFieldCorrectionFlag");
    }
```

2021-03-17 09:57 UTC, hott-onin commented on specifics/SpectrumOneCCD/SpectrumOneCCD.cpp
> +    //     yat4tango::InnerAppender::initialize(this, 512);
L'inner-appender n'a jamais fonctionné correctement lors des inits si ajouté aux devices spécifiques, ICALIMA-83

2021-03-17 10:02 UTC, hott-onin commented on doc/SpectrumOneCCD/spectrumoneccd.rst
> +GpibAddress             0                                       Long            Gpib Address of the controller (from 0 to 30).
Je ne vois pas le problème, que faut-il faire, renommer la propriété?
La description me semble claire, il y a trois propriétés, host, port, gpibAdress

2021-03-17 10:03 UTC, hott-onin commented on doc/SpectrumOneCCD/spectrumoneccd.rst
> +lastTemperature         Read            Double          Last temperature of the CCD.
Parce que ce n'est pas la temperature réelle, mais la derniére température trouvée.
La température n'est lue que quand la commande GetTemperature est exécutée

2021-03-17 10:04 UTC, hott-onin commented on doc/SpectrumOneCCD/spectrumoneccd.rst
> +ForcedInit              Void            Void            Force the initialization, injection of the tables and the re-configuration of the camera.
Cette commande permet de remvoyer les tables dans la caméra. Alors qu'avec init, si la caméra est déjà configurée, les tables ne sont pas envoyées.

2021-03-17 10:05 UTC, hott-onin commented on doc/SpectrumOneCCD/spectrumoneccd.rst
> +GetGain                 Void            Void            Get the temperature of the camera.
Modifié

2021-03-17 10:05 UTC, hott-onin commented on specifics/SpectrumOneCCD/SpectrumOneCCD.cpp
> +    CREATE_SCALAR_ATTRIBUTE(attr_gain_read);
Modifié

2021-03-17 10:06 UTC, hott-onin commented on specifics/SpectrumOneCCD/SpectrumOneCCD.cpp
> +
Quel est l'intérêt de ce code?

2021-03-17 10:10 UTC, hott-onin commented on specifics/SpectrumOneCCD/SpectrumOneCCD.cpp
> +    m_camera->getTemperature(*attr_lastTemperature_read);
getTemperature n'est pas susceptible de lever une exception.
Quel est l'intérêt de catch une exception si c'est pour la re-throw directement?
Il ne me semble pas nécéssaire de l'ajouter au status manuellement?
Je ne suis pas convaincu de l'utilité du lock, je vais regarder ça

2021-03-17 10:15 UTC, hott-onin commented on doc/SpectrumOneCCD/spectrumoneccd.rst
> +ForcedInit              Void            Void            Force the initialization, injection of the tables and the re-configuration of the camera.
Il semble que la caméra ne se comporte pas correctement suite au renvoi des tables, je supprime cette commande

2021-03-17 10:39 UTC, hott-onin commented on doc/SpectrumOneCCD/spectrumoneccd.rst
> +ReConfig                Void            Void            Force the re-configuration of the camera.
Modifié par ForceConfig

2021-03-17 10:40 UTC, hott-onin commented on specifics/SpectrumOneCCD/SpectrumOneCCD.cpp
> +
Gain et NumFlushes mémorisés via configuration Pogo

2021-03-18 16:04 UTC, soleil-ica commented on specifics/SpectrumOneCCD/SpectrumOneCCD.cpp
> +
OK: vu avec Arafat: tu peux tester sans ce code. il faut tout de même mettre de dev_state()

2021-03-18 16:09 UTC, soleil-ica commented on specifics/SpectrumOneCCD/SpectrumOneCCD.cpp
> +    m_camera->getTemperature(*attr_lastTemperature_read);
Pour le Status ok: pas besoin (j'avais récupéré un vieux code)
pour le catch es tu sur à 100 % qu'il n'y a pas d'exception ? si une lima::Exception est levée: alors personne ne la catch et le process termine. pour les DevFailed, il y a en effet Tango qui catch.
le rethrow permet de rajouter de la sémantique si necessaire

2021-03-26 13:20 UTC, hott-onin commented on doc/SpectrumOneCCD/spectrumoneccd.rst
> +GpibAddress             0                                       Long            Gpib Address of the controller (from 0 to 30).
Modifié

2021-03-26 13:31 UTC, hott-onin commented on specifics/SpectrumOneCCD/SpectrumOneCCD.cpp
> +
Modifié

2021-03-26 13:40 UTC, hott-onin commented on specifics/SpectrumOneCCD/SpectrumOneCCD.cpp
> +    m_camera->getTemperature(*attr_lastTemperature_read);
Ok

2021-03-26 13:42 UTC, hott-onin commented on specifics/SpectrumOneCCD/SpectrumOneCCD.cpp
> +
Pogo pas fiable, faire à la main

2021-04-12 09:27 UTC, soleil-ica approved these changes

2021-04-12 09:27 UTC, merged