[CTRLRFC-1194][Hamamatsu] Add hability to manage Kind and Polarity output trigger options to Hamamatsu camera
soleil-ica/Lima-tango-cpp pull request #36
Opened 2021-06-15 09:35 UTC by goldensgui

Add read and write methods to allow management of the KIND and POLARITY options related to equipment output triggers :

 - Read : 
   - void Hamamatsu::read_channel1Polarity(Tango::Attribute &attr)
   - void Hamamatsu::read_channel2Polarity(Tango::Attribute &attr)
   - void Hamamatsu::read_channel3Polarity(Tango::Attribute &attr)
   - void Hamamatsu::read_channel1Kind(Tango::Attribute &attr)
   - void Hamamatsu::read_channel2Kind(Tango::Attribute &attr)
   - void Hamamatsu::read_channel3Kind(Tango::Attribute &attr)

 - Write:
    - void Hamamatsu::write_channel1Polarity(Tango::WAttribute &attr)
    - void Hamamatsu::write_channel2Polarity(Tango::WAttribute &attr)
    - void Hamamatsu::write_channel3Polarity(Tango::WAttribute &attr)
    - void Hamamatsu::write_channel1Kind(Tango::WAttribute &attr)
    - void Hamamatsu::write_channel2Kind(Tango::WAttribute &attr)
    - void Hamamatsu::write_channel3Kind(Tango::WAttribute &attr)

 - Attributes created : 
     - attr_channel1Kind
     - attr_channel2Kind 
     - attr_channel3Kind
     - attr_channel1Polarity
     - attr_channel2Polarity
     - attr_channel3Polarity

2021-06-15 17:03 UTC, soleil-ica requested changes

2021-06-15 17:03 UTC, soleil-ica commented on specifics/Hamamatsu/HamamatsuStateMachine.cpp
> +//+----------------------------------------------------------------------------
no State machine? at least INIT and FAULT, maybe RUNNING ?

2021-06-15 17:03 UTC, soleil-ica commented on specifics/Merlin/MerlinClass.cpp
> +    gain_prop.set_description("0 = SLGM \n1 = LGM\n2 = HGM\n3 = SHGM");
I still don't understand why this commit appear there ... I hope that for the next commit, all the stuff from Hamamatsu will not be there... (did you do a pull before starting to work ?)

2021-06-15 17:03 UTC, soleil-ica commented on src/LimaDetector.cpp
> +		//yat4tango::YatLogAdapter::initialize(this);
uncomment

2021-06-15 17:03 UTC, soleil-ica commented on src/LimaDetector.cpp
> +	//yat4tango::YatLogAdapter::release();
uncomment

2021-06-17 16:17 UTC, soleil-ica requested changes

2021-06-18 09:57 UTC, goldensgui commented on doc/Hamamatsu/hamamatsu.rst
> +channel3Polarity	R/W	   UShort     Polarity for channel 3 (NEGATIVE = 1, POSITIVE = 2).
SDK uses those values and we didn't want to interfere with its usage. Value can be corrected if needed/more convenient for user

2021-06-18 12:50 UTC, soleil-ica commented on doc/Hamamatsu/hamamatsu.rst
> +channel3Polarity	R/W	   UShort     Polarity for channel 3 (NEGATIVE = 1, POSITIVE = 2).
we agreed to use: NEGATIVE = 0, POSITIVE = 1

2021-06-18 12:50 UTC, soleil-ica approved these changes

2021-06-18 12:56 UTC, soleil-ica approved these changes

2021-06-18 13:49 UTC, soleil-ica approved these changes

2021-06-18 18:39 UTC, soleil-ica requested changes

2021-06-18 18:39 UTC, soleil-ica commented on specifics/Hamamatsu/Hamamatsu.cpp
> +#include <string.h>
string.h should be removed I think

2021-06-18 18:39 UTC, soleil-ica commented on specifics/Hamamatsu/Hamamatsu.cpp
> +    catch(Tango::DevFailed & df)
not properly aligned

2021-06-18 18:39 UTC, soleil-ica commented on specifics/Hamamatsu/Hamamatsu.cpp
> +    catch(Tango::DevFailed & df)
idem

2021-06-21 07:20 UTC, soleil-ica approved these changes

2021-06-21 07:22 UTC, merged