[CTRLRFC-980] Dhyana evolution
soleil-ica/Lima-tango-cpp pull request #40
Opened 2021-09-23 09:26 UTC by goldensgui

Add Frame rate attribute and implement trigger output

2021-09-24 13:33 UTC, soleil-ica requested changes

2021-09-24 13:33 UTC, soleil-ica commented on specifics/Dhyana/Dhyana.h
> +enum class edgeMode : short
Set the 1st letter in CAPITAL case

2021-09-24 13:33 UTC, soleil-ica commented on specifics/Dhyana/Dhyana.h
> +	GLOBAL
add a k and use the mixed case notation, eg: kExposureStart 

idem for all Enums

2021-09-24 13:33 UTC, soleil-ica commented on specifics/Dhyana/Dhyana.h
> +	lima::Dhyana::Camera::TucamSignal signal3;
add a m_ before the members names

2021-09-24 13:33 UTC, soleil-ica commented on specifics/Dhyana/DhyanaStateMachine.cpp
> +		return true;
The state machine is wrong (because of Pogo 9): please see with Arafat to manage it together

2021-09-27 13:55 UTC, soleil-ica commented on specifics/Dhyana/Dhyana.cpp
> +	/*----- PROTECTED REGION END -----*/	//	Dhyana::get_device_property_after
Checked with Kewin: they have to be memorised

2021-09-27 13:59 UTC, soleil-ica requested changes

2021-09-28 05:50 UTC, goldensgui commented on specifics/Dhyana/DhyanaClass.cpp
> +	delay1->set_disp_level(Tango::EXPERT);
Yes, line 800 : delay1_prop.set_unit("ms");

2021-09-28 06:56 UTC, soleil-ica approved these changes

2021-09-28 06:58 UTC, soleil-ica approved these changes

2021-09-28 07:04 UTC, merged