Update Lambda.rst
soleil-ica/Lima-tango-cpp pull request #43
Opened 2022-04-27 12:50 UTC by SixtineHostache

Modification of Lambda.rst after the addition of several new attributes

2022-04-27 13:10 UTC, SixtineHostache commented
Update of Lambda specific after a check (done by hand due to some GIT issues)

2022-05-02 14:45 UTC, soleil-ica requested changes

2022-05-02 14:45 UTC, soleil-ica commented on specifics/Lambda/Lambda.cpp
> +    CREATE_DEVSTRING_ATTRIBUTE(attr_configFilesPath_read, Lambda_ns::CONFIG_FILES_PATH_SIZE_MAX);
enlever les "path_size_max" qui sont deja à 255 par defaut

2022-05-02 14:45 UTC, soleil-ica commented on specifics/Lambda/Lambda.cpp
> +        sleep (1);
a quoi sert le sleep ?
pour le distortionCorrection: dans l'init_device il faut ecrire la valeur de la propriété via setDistortionCorrection;
pas besoin de faire un read, il sera fait dans le read attribute

2022-05-02 14:45 UTC, soleil-ica commented on specifics/Lambda/Lambda.cpp
> +        //attr.set_quality(Tango::ATTR_VALID);
ce code la doit etre fait dans le init_device, une fois pour toute
et enlever le set_quality

2022-05-02 14:45 UTC, soleil-ica commented on specifics/Lambda/Lambda.cpp
> +        m_camera->getDistortionCorrection(w_distortionCorrection);
enlever le set_quality(valid)

2022-05-02 14:45 UTC, soleil-ica commented on specifics/Lambda/Lambda.cpp
> +	set_state(Tango::STANDBY);
enlever le set_state

2022-05-02 14:45 UTC, soleil-ica commented on specifics/Lambda/Lambda.cpp
> +		*attr_energyThreshold_read = w_energyThreshold;
à remplacer par:
m_camera->getEnergyThreshold(*attr_energyThreshold_read);

2022-05-02 14:45 UTC, soleil-ica commented on specifics/Lambda/Lambda.cpp
> +        m_camera->setEnergyThreshold(data);
à remplacer par:
m_camera->setEnergyThreshold(w_val);

et:
il faut memoriser la valeur via:
yat4tango::PropertyHelper::set_property(this, "MemorizedEnergyThreshold", w_val);

2022-05-02 14:45 UTC, soleil-ica commented on specifics/Lambda/Lambda.cpp
> +        INFO_STREAM      << "Write_energyThreshold FAILED" << endl;
pourquoi ce catch(...) ?

2022-05-02 14:45 UTC, soleil-ica commented on specifics/Lambda/Lambda.cpp
> +		strcpy(*attr_libraryVersion_read, w_libVersion.c_str());
deplacer ce code dans le init_device, de sorte qu'il soit executé qu'une seule fois

2022-05-02 14:45 UTC, soleil-ica commented on specifics/Lambda/Lambda.cpp
> +		//if the boolean returns false it means that this function is not supported by the firmware.
if the function returns false

2022-05-02 14:45 UTC, soleil-ica commented on specifics/Lambda/Lambda.cpp
> +		if (w_has_feature){
à simplifier par if (m_camera->hasFeature(xsp::lambda::Feature::FEAT_HV)
{
...
}

2022-05-02 14:45 UTC, soleil-ica commented on specifics/Lambda/Lambda.cpp
> +        	*attr_highVoltage_read = w_highVoltage;
à simplifier par m_camera->getHighVoltage(*attr_highVoltage_read);

2022-05-02 14:45 UTC, soleil-ica commented on specifics/Lambda/Lambda.cpp
> +			INFO_STREAM << "highVoltage is not supported by the firmware" << endl;
enlever le INFO_STREAM

2022-05-02 14:45 UTC, soleil-ica commented on specifics/Lambda/Lambda.cpp
> +        double w_humidity = 99.99;
plutot = -1

2022-05-02 14:45 UTC, soleil-ica commented on specifics/Lambda/Lambda.cpp
> +			INFO_STREAM << "humidity is not supported by the firmware" << endl;
enlever le stream

2022-05-02 14:45 UTC, soleil-ica commented on specifics/Lambda/Lambda.cpp
> +			INFO_STREAM << "temperature is not supported by the firmware" << endl;
idem

2022-05-02 14:45 UTC, soleil-ica commented on specifics/Lambda/Lambda.cpp
>      (this->*in_write_method)(attribute);
supprimer cette fonction: write_property_in_string_static_attribute (car non utilisée)

2022-05-02 14:45 UTC, soleil-ica commented on specifics/Lambda/Lambda.cpp
> +    write_property_in_static_attribute("energyThreshold", attr_energyThreshold_read, memorizedEnergyThreshold, &Lambda::write_energyThreshold);
ne pas utiliser cette fonction (et donc la supprimer dans son .hpp et supprimer le .hpp)
utiliser à la place:
```
INFO_STREAM << "Write tango hardware at Init - energyThreshold." << endl;
Tango::WAttribute &energyThreshold = dev_attr->get_w_attr_by_name("energyThreshold");
attr_energyThreshold_write = memorizedEnergyThreshold;
energyThreshold.set_write_value(attr_energyThreshold_write);
write_energyThreshold(energyThreshold);
```

2022-05-02 14:45 UTC, soleil-ica commented on specifics/Lambda/Lambda.cpp
> +// //--------------------------------------------------------
supprimer tout ce code, qui a du etre commenté par Pogo

2022-05-02 14:45 UTC, soleil-ica commented on src/LimaDetector.cpp
> +		if(dev_state() == Tango::RUNNING && !expertUsePrepareCmd)//mantis #22238
il faut que tu annules tes modifs sur ce fichier, car tu ne dois pas le modifier
je pense qu'il faut que tu fasses un pull pour te mettre à jour

2022-05-02 14:45 UTC, soleil-ica commented on src/LimaDetector.h
> + *	- Dhyana<br>
il faut que tu annules tes modifs sur ce fichier, car tu ne dois pas le modifier
je pense qu'il faut que tu fasses un pull pour te mettre à jour

2022-05-02 14:45 UTC, soleil-ica commented on src/LimaDetectorClass.cpp
> +	prop_desc = "Define the type of the connected Detector .<BR>\nAvailables types :<BR>\n- AndorCCD<BR>\n- BaslerCCD<BR>\n- Eiger<br>\n- Hamamatsu<br>\n- ImXpad<br>\n- MarCCD<BR>\n- Maxipix <BR>\n- Mer
il faut que tu annules tes modifs sur ce fichier, car tu ne dois pas le modifier
je pense qu'il faut que tu fasses un pull pour te mettre à jour

2022-05-02 14:45 UTC, soleil-ica commented on src/main.cpp
> +#ifndef LINUX64_NO_CRASH_REPORT //maxipix 64 bits, because crash report not yet supported
il faut que tu annules tes modifs sur ce fichier, car tu ne dois pas le modifier
je pense qu'il faut que tu fasses un pull pour te mettre à jour

2022-06-02 16:05 UTC, SixtineHostache commented on specifics/Lambda/Lambda.cpp
> +        sleep (1);
Il a été enlevé

2022-06-02 16:23 UTC, SixtineHostache commented on specifics/Lambda/Lambda.cpp
>      (this->*in_write_method)(attribute);
Elle est appelée par la fonction write at init qui est appelée dans le init_device

2022-06-02 16:26 UTC, SixtineHostache commented on specifics/Lambda/Lambda.cpp
> +    write_property_in_static_attribute("energyThreshold", attr_energyThreshold_read, memorizedEnergyThreshold, &Lambda::write_energyThreshold);
Qu'entends tu par "la supprimer dans son .hpp et supprimer le .hpp" ?

2022-06-10 14:23 UTC, closed without merging

2022-06-10 14:23 UTC, soleil-ica commented
merged by an external tool