Hamamatsu - LimaDetector: If Specific is in FAULT state during intialization the LimaDetector is in FAUTL state too
soleil-ica/Lima-tango-cpp pull request #61
Opened 2023-04-17 10:11 UTC by sbahji

[ICATHALES-464][Hamamatsu] If Specific is FAULT during init_device the LimaDetector

2023-04-18 16:08 UTC, soleil-ica requested changes

2023-04-18 16:08 UTC, soleil-ica commented on specifics/Hamamatsu/Hamamatsu.cpp
> +        if(m_is_device_initialized)
ajouter un commentaire

2023-04-18 16:08 UTC, soleil-ica commented on src/Factory.cpp
> +    if(m_state != Tango::FAULT)
ajouter un commentaire: pourquoi si state != Fault?

2023-04-20 06:08 UTC, sbahji commented on specifics/Hamamatsu/Hamamatsu.cpp
> +        if(m_is_device_initialized)
ok

2023-04-20 06:08 UTC, sbahji commented on src/Factory.cpp
> +    if(m_state != Tango::FAULT)
ok

2023-04-21 08:47 UTC, soleil-ica approved these changes

2023-04-21 08:48 UTC, merged